### PR TITLE
Universal instance type

### PR DESCRIPTION
**Pull request by nmenardg**
https://www.pivotaltracker.com/story/show/126630419
https://www.pivotaltracker.com/story/show/128009829

### CODE REVIEW

**Comment by oleduc** [comment]
Approved.

**Comment by nikitagromov** [comment]
Are all unit tests passed after this changes ?

**Comment by nmenardg** [comment]
@nikitagromov With all the changes from the 4 repositories, yes. There was a lot to adapt in cerri-api

**Comment by nikitagromov** [comment]
Approved

**Pull request merged**
